from fastapi import FastAPI
import yfinance as yf
import pandas as pd

app = FastAPI()

def detect_trend(df):
    if df.empty or len(df) < 50:
        return "No Trend (insufficient data)"
    
    df["EMA20"] = df["Close"].ewm(span=20).mean()
    df["EMA50"] = df["Close"].ewm(span=50).mean()

    if df["EMA20"].iloc[-1] > df["EMA50"].iloc[-1]:
        return "Bullish"
    return "Bearish"

def detect_mss(df):
    if df.empty or len(df) < 3:
        return "No MSS (insufficient data)"

    last = float(df["Close"].iloc[-1])
    prev = float(df["Close"].iloc[-2])

    if last > prev:
        return "Bullish MSS"
    return "Bearish MSS"

def detect_order_block(df):
    if df.empty or len(df) < 10:
        return {
            "bullish_OB": None,
            "bearish_OB": None,
            "note": "Not enough data for OB"
        }

    last_low = float(df["Low"].iloc[-10:-1].min())
    last_high = float(df["High"].iloc[-10:-1].max())

    return {
        "bullish_OB": round(last_low, 2),
        "bearish_OB": round(last_high, 2)
    }

@app.get("/")
def home():
    return {"status": "HOENX AI Backend Running 🚀", "usage": "/analysis?ticker=TCS.NS"}

@app.get("/analysis")
def analysis(ticker: str = "TCS.NS"):
    try:
        # HTF Bias - Daily timeframe
        daily = yf.download(ticker, period="6mo", interval="1d")

        # LTF Execution - 5m timeframe
        m5 = yf.download(ticker, period="5d", interval="5m")

        if daily.empty:
            return {"error": f"Daily data unavailable for {ticker}"}

        if m5.empty:
            return {"error": f"5m data unavailable for {ticker}"}

        bias = detect_trend(daily)
        mss = detect_mss(m5)
        ob = detect_order_block(m5)

        return {
            "ticker": ticker,
            "daily_bias": bias,
            "mss": mss,
            "order_blocks": ob,
            "note": "Signal generated by HOENX-AI MTF v1 Model"
        }

    except Exception as e:
        return {"error": str(e)}
